name: Generate Snake Animation

on:
  schedule:
    - cron: "0 3 * * *"   # roda todo dia às 3h
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: duartexz-dev
          outputs: |
            assets/contribution-snake-dark.svg?palette=github-dark
            assets/contribution-snake.svg

      - name: Push assets to a assets branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
